[build]
  command = "npx prisma generate && npm run verify:netlify && npx prisma db push --skip-generate && npm run db:seed"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
